// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZFnXWFXSvXrEbPGNbmiMLslEsBlhrg14',
    appId: '1:232750363541:web:fb52e6a668f532e9687c9c',
    messagingSenderId: '232750363541',
    projectId: 'mynotes-portfolio-app',
    authDomain: 'mynotes-portfolio-app.firebaseapp.com',
    storageBucket: 'mynotes-portfolio-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeg1pDTDIlmuuVsZSZGs5xuspImYDpmPk',
    appId: '1:232750363541:android:c5e2e451e6dc91d7687c9c',
    messagingSenderId: '232750363541',
    projectId: 'mynotes-portfolio-app',
    storageBucket: 'mynotes-portfolio-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgUsuuImAjKAzqrmvEchuOtu3Jfse_jfw',
    appId: '1:232750363541:ios:5451626d79bf9679687c9c',
    messagingSenderId: '232750363541',
    projectId: 'mynotes-portfolio-app',
    storageBucket: 'mynotes-portfolio-app.appspot.com',
    iosClientId: '232750363541-06fe17fhor2ehcufegslifg64296id8b.apps.googleusercontent.com',
    iosBundleId: 'com.fabsfitt.mynotes',
  );
}
